#!/bin/sh
cd /usr/bin
echo "arecordmidi----------------"
ldd arecordmidi
echo "ccmakedep----------------"
ldd ccmakedep
echo "cpan----------------"
ldd cpan
echo "db_printlog----------------"
ldd db_printlog
echo "ecpg----------------"
ldd ecpg
echo "fprintd-enroll----------------"
ldd fprintd-enroll
echo "glxinfo64----------------"
ldd glxinfo64
echo "gst-launch----------------"
ldd gst-launch
echo "htmex----------------"
ldd htmex
echo "ipcmk----------------"
ldd ipcmk
echo "kdialog----------------"
ldd kdialog
echo "last----------------"
ldd last
echo "lsattr----------------"
ldd lsattr
echo "mobj_dump----------------"
ldd mobj_dump
echo "nproc----------------"
ldd nproc
echo "pamchannel----------------"
ldd pamchannel
echo "pbmmask----------------"
ldd pbmmask
echo "pgmmake----------------"
ldd pgmmake
echo "pngtopnm----------------"
ldd pngtopnm
echo "posplit----------------"
ldd posplit
echo "ps2pdf14----------------"
ldd ps2pdf14
echo "repoquery----------------"
ldd repoquery
echo "sbcl----------------"
ldd sbcl
echo "smbcacls----------------"
ldd smbcacls
echo "systemd-firstboot----------------"
ldd systemd-firstboot
echo "tracker-search----------------"
ldd tracker-search
echo "whatis----------------"
ldd whatis
echo "xmltex----------------"
ldd xmltex
echo "----------------"
